### ISSUE TITLE
RTTL Not working.

### ISSUE THREAD

**Issue by monsieurlatte** [gabe565/esphome-configs#16]
So I kind of did a hodgepodge and I like this to not rely on other packages or links to other yaml files so I just copied and replaced things from config to opengarage and all that into one yaml.  If I use the rttl command from HA it plays sounds fine so I know the GPIO is right and all that but for some reason it doesn't play when I turn on the alarm button in the web or if I use the open/close commands.  I'll attached my yaml with removed important things, if someone could review for me.

[garage-door.yaml.zip](https://github.com/gabe565/esphome-configs/files/11013066/garage-door.yaml.zip)

**Comment by gabe565** [comment]
Hey! I'd suggest trying to use it as a package. I update the OpenGarage config occasionally and it'll be harder for you to update your local config with my changes if you merge them together. Have you tried it as a package yet? I'll verify the RTTTL config is correct in this repo. It's possible that I made an error when copying from my local config.

**Comment by monsieurlatte** [comment]
Bashfully going to come in here and state that upon reading through more of your configs, it seems the alarm will only trigger when you have the alarm switch turned on...I ass/u/me/d that those were just to manually trigger the alarm sounds and not to tell if it was to play or not.  Is that correct?

**Comment by gabe565** [comment]
Ah sorry for the misunderstanding! Yep, those toggles enable or disable the alarm when opening/closing the garage door. Do they work like that for you?

**Comment by gabe565** [comment]
If you have a use for it, you could add a button to trigger the alarm manually!

**Comment by monsieurlatte** [comment]
Once I realized what they did I didnt mess with them anymore, I just kept my version of the config (based on all your hard work :) ), thanks for doing this!  Much happier with it.
